# Generated by Django 4.1.3 on 2022-11-26 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='account_type',
            field=models.CharField(choices=[('Elderly Member', 'eld'), ('Volunteer', 'vol')], max_length=200),
        ),
    ]
