# Generated by Django 4.1.3 on 2022-11-16 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='activity_id',
            new_name='id',
        ),
    ]
