# Generated by Django 3.0.1 on 2022-12-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
