# Generated by Django 3.0.1 on 2022-12-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_requests', '0003_auto_20221203_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
